### ISSUE TITLE
Long term data storage

### ISSUE THREAD

**Issue by yuvadm** [erlichsefi/israeli-supermarket-scarpers#18]
Awesome project! Are you storing the scraped data somewhere?

**Comment by erlichsefi** [comment]
Hi @yuvadm! Thank you! 
Long-term storage for all the data is still TBD, I had some trials with that but stopped because of the raw amount of data that needs to be stored. I planned to process the data and distill the minimal amount of data needed, but I couldn't find the time.

For the time being, we integrated with https://github.com/korenLazar/supermarket-scraping which stores some of the data. 
If you are interested in contributing let me know, my vision is a proper publicly accessible API with additional information about the brand, like:
-  Is the brand monopoly in that sector?
-  Allegheny information.
- etc...
