### ISSUE TITLE
mega provider doesn't download stores

### ISSUE THREAD

**Issue by AKorets** [erlichsefi/israeli-supermarket-scarpers#24]
The mega provider loading zero stores (some times)
first loading done by this line:
```
        ScarpingTask(dump_folder_name=output_folder, only_latest=True,
                                        files_types=[FileTypesFilters.STORE_FILE.name],
                                        enabled_scrapers=[scrapper],
                                        lookup_in_db=False).start()
```
second loading done when parameter `only_latest=False`
with same result
`Total size of data_stores/mega: 0.0 MB`
full log at this link
https://github.com/AKorets/israeli-supermarket-data/actions/runs/5685290255/job/15409844796

**Comment by erlichsefi** [comment]
Looking at the logs the link you've provided:
```
Logger       2023-07-27 20:46:56,633 INFO     logger.py:info On a new Session requesting url: http://publishprice.mega.co.il/
Logger       2023-07-27 20:46:58,963 INFO     logger.py:info Last folder is ncr/
Logger       2023-07-27 20:46:58,963 INFO     logger.py:info On a new Session requesting url: http://publishprice.mega.co.il/ncr/
```
It seems that the scraper going to `http://publishprice.mega.co.il/ncr/` instead of `http://publishprice.mega.co.il/20230727/`

The behavior was changed [here](https://github.com/erlichsefi/israeli-supermarket-scarpers/commit/3693b40ceda81ccc8f0ae8a4359d3d642fea0505) but wasn't released yet.  
I release soon.

**Comment by erlichsefi** [comment]
You can now update to [0.3](https://pypi.org/project/il-supermarket-scraper/).
please close the issue if the update fix it.
